const fakeData = {
    all: [
        { key: 1, name: 'Diploma Engineering', img: 'https://sanskriti.edu.in/blog/wp-content/uploads/2018/08/about_eng.jpg', },
        { key: 2, name: 'Basic Computer Courses', img: 'https://iatntrainingnepal.com/wp-content/uploads/2020/08/basic-computer.png', },
        { key: 3, name: 'Short Courses', img: 'https://scontent.fdac5-2.fna.fbcdn.net/v/t1.6435-9/172739079_145567007504973_7942829011045659202_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=730e14&_nc_ohc=qPMSMPLYSq0AX-Yh13P&tn=n1Pe14gPZ38CZFbp&_nc_ht=scontent.fdac5-2.fna&oh=e172593d959d4ca7090971a7a4f3ddcf&oe=61822E44', },
        { key: 4, name: 'Outsourcing Courses', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4AQsXW460158Xzl9KIjE-BPnDS2RQGuIn7Q&usqp=CAU', },
    ],
    diploma: [
        { key: 1, name: 'Civil Engineering', img: 'http://indiraicem.ac.in/blog/wp-content/uploads/2020/09/WhatsApp-Image-2020-08-24-at-1.26.50-PM-2.jpeg', detail: 'Civil engineering is a professional engineering discipline that deals with the design, construction, and maintenance of the physical and naturally built environment, including public works such as roads, bridges, canals, dams, airports, sewage systems, pipelines, structural components of buildings, and railways.' },
        { key: 2, name: 'Computer Engineering', img: 'https://image.freepik.com/vetores-gratis/conceito-de-engenharia-de-computador-plana_23-2148159419.jpg', detail: 'Computer engineering is a branch of engineering that integrates several fields of computer science and electronic engineering required to develop computer hardware and software.' },
        { key: 3, name: 'Electrical Engineering', img: 'https://www.freestudy.com/wp-content/uploads/2019/08/Best-Free-Online-Electrical-Engineering-Courses-800x542.jpg?ezimgfmt=rs:314x213/rscb1/ng:webp/ngcb1', detail: 'Electrical engineering is an engineering discipline concerned with the study, design and application of equipment, devices and systems which use electricity, electronics, and electromagnetism.' },
        { key: 4, name: 'Mechanical Engineering', img: 'https://www.pngitem.com/pimgs/m/356-3565431_mechanical-engineering-group-icon-hd-png-download.png', detail: 'Mechanical engineering is an engineering branch that combines engineering physics and mathematics principles with materials science to design, analyze, manufacture, and maintain mechanical systems.It is one of the oldest and broadest of the engineering branches.' },
        { key: 5, name: 'Textile Engineering', img: 'https://cdn.slidesharecdn.com/ss_thumbnails/textileengineering-170119044353-thumbnail-4.jpg?cb=1484801192', detail: 'Textile manufacturing is a major industry. It is largely based on the conversion of fibre into yarn, then yarn into fabric. These are then dyed or printed, fabricated into cloth which is then converted into useful goods such as clothing, household items, upholstery and various industrial products.' },
    ],
    basic: [
        { name: 'Microsoft Word Basic Course', img: 'https://www.inspizone.com/wp-content/uploads/2019/07/Words-Basic.png', detail: 'Microsoft Word is a word processing software developed by Microsoft. It was first released on October 25, 1983, under the name Multi-Tool Word for Xenix systems.' },
        { name: 'Microsoft Excel Basic Course', img: 'https://www.bamiviledu.org/courses/wp-content/uploads/2020/10/yIAurNCQbfTMsDdjU03d8fde48-1e0c-4b28-b596-35b1df1e413c.jpeg', detail: 'Microsoft Excel is a spreadsheet developed by Microsoft for Windows, macOS, Android and iOS. It features calculation, graphing tools, pivot tables, and a macro programming language called Visual Basic for Applications (VBA).' },
        { name: 'Microsoft Power Point Basic Course', img: 'https://www.filepicker.io/api/file/ou95i4xGQXm3iqTbtTwt', detail: '' },
        { name: 'Microsoft Access Basic Course', img: 'https://www.filepicker.io/api/file/KY7u4cqwSkCOgCbc8rYd', detail: 'Microsoft Access is a database management system (DBMS) from Microsoft that combines the relational Microsoft Jet Database Engine with a graphical user' },
        { name: 'Microsoft Outlook Basic Course', img: 'https://etindy.com/wp-content/uploads/outlook-hero.png', detail: 'Microsoft Outlook is a personal information manager software system from Microsoft, available as a part of the Microsoft Office suite. Though primarily an email client, Outlook also includes such functions as calendaring, task managing, contact managing, note-taking, journal logging, and web browsing.' }
    ],
    short: [
        { name: 'Auto Cad Basic Course', img: 'https://5.imimg.com/data5/JB/BA/GLADMIN-6873332/autocad-course-500x500.jpg', detail: 'AutoCAD is a commercial computer-aided design (CAD) and drafting software application. Developed and marketed by Autodesk,[1] AutoCAD was first released in December 1982 as a desktop app running on microcomputers with internal graphics controllers.' },
        { name: 'Sewing machine Full Course', img: 'https://5.imimg.com/data5/AY/RU/GLADMIN-34100949/sewing-machine-operator-course-500x500.jpg', detail: 'A sewing machine is a machine used to sew fabric and materials together with thread. Sewing machines were invented during the first Industrial Revolution' },

    ],
    outsourcing: [
        { Name: 'Basic Web Development Course', img: 'https://www.onlinecoursereport.com/wp-content/uploads/2020/07/shutterstock_394793860-1024x784.jpg', detail: 'Web development is the work involved in developing a Web site for the Internet (World Wide Web) or an intranet (a private network). Web development can range from developing a simple single static page of plain text to complex web applications, electronic businesses, and social network services' },
        { Name: 'Advance Graphic Designing Course', img: 'https://static.skillshare.com/uploads/video/thumbnails/3ccfb0086a3a7b609c905750075bd1cf/448-252', detail: 'Graphic design is the profession and academic discipline whose activity consists in projecting visual communications intended to transmit specific messages to social groups, with specific objectives.' },
        { Name: 'Digital Marketing Course', img: 'https://cosmosgroup.sgp1.cdn.digitaloceanspaces.com/thumbnail/lead/news/2427717_free%20digital%20marketing%20course.jpg', detail: 'Digital marketing is the component of marketing that utilizes internet and online based digital technologies such as desktop computers, mobile phones and other digital media and platforms to promote products and services.' },
        { Name: 'Lead Generation Course', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTshwomYQPfb2ws5WCVyJx_hkVBMWMrnKqWYP9cPd9rgWCqe7eXinsonofEnyiQCfuDgNI&usqp=CAU', detail: 'lead generation is the initiation of consumer interest or enquiry into products or services of a business. Leads can be created for purposes such as list building, e-newsletter list acquisition or for sales leads.' },
    ]
}